# Generated by Django 5.2.6 on 2025-09-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecg_app', '0002_alter_ecgimage_options_ecgimage_analysis_results_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecgimage',
            name='patient_age',
            field=models.PositiveIntegerField(blank=True, help_text="Patient's age in years", null=True),
        ),
        migrations.AddField(
            model_name='ecgimage',
            name='patient_name',
            field=models.CharField(blank=True, help_text="Patient's full name", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ecgimage',
            name='patient_phone',
            field=models.CharField(blank=True, help_text="Patient's phone number", max_length=20, null=True),
        ),
    ]
