# Generated by Django 5.2.6 on 2025-09-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecg_app', '0003_ecgimage_patient_age_ecgimage_patient_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecgimage',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text="Patient's date of birth", null=True),
        ),
    ]
