# Generated by Django 5.2.6 on 2025-09-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecg_app', '0004_ecgimage_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecgimage',
            name='date_of_birth',
        ),
        migrations.AlterField(
            model_name='ecgimage',
            name='patient_age',
            field=models.PositiveIntegerField(default=0, help_text="Patient's age in years"),
        ),
        migrations.AlterField(
            model_name='ecgimage',
            name='patient_name',
            field=models.CharField(default='Unknown Patient', help_text="Patient's full name", max_length=255),
        ),
        migrations.AlterField(
            model_name='ecgimage',
            name='patient_phone',
            field=models.CharField(default='Not provided', help_text="Patient's phone number", max_length=20),
        ),
    ]
