# Generated by Django 5.1.4 on 2025-09-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecg_app', '0005_remove_ecgimage_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecgimage',
            name='patient_age',
            field=models.PositiveIntegerField(help_text="Patient's age in years"),
        ),
        migrations.AlterField(
            model_name='ecgimage',
            name='patient_name',
            field=models.CharField(help_text="Patient's full name", max_length=255),
        ),
        migrations.AlterField(
            model_name='ecgimage',
            name='patient_phone',
            field=models.CharField(help_text="Patient's phone number", max_length=20),
        ),
    ]
