# Generated by Django 5.1.4 on 2025-09-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecg_app', '0006_alter_ecgimage_patient_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecgimage',
            name='patient_dob',
            field=models.DateField(help_text="Patient's date of birth", null=True),
        ),
    ]
