# Generated by Django 5.1.4 on 2025-10-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecg_app', '0007_ecgimage_patient_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='EchoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(help_text="Patient's full name", max_length=255)),
                ('patient_age', models.PositiveIntegerField(help_text="Patient's age in years")),
                ('patient_dob', models.DateField(help_text="Patient's date of birth", null=True)),
                ('patient_phone', models.CharField(help_text="Patient's phone number", max_length=20)),
                ('patient_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('echo_file', models.FileField(upload_to='echo_uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('analysis_results', models.JSONField(blank=True, null=True)),
                ('ejection_fraction', models.FloatField(blank=True, null=True)),
                ('lv_function', models.CharField(blank=True, max_length=50, null=True)),
                ('wall_motion', models.CharField(blank=True, max_length=100, null=True)),
                ('image_quality', models.CharField(blank=True, max_length=50, null=True)),
                ('overall_impression', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
