# Generated by Django 5.1.4 on 2025-10-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecg_app', '0008_echoimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecgimage',
            name='patient_gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', help_text="Patient's gender", max_length=10),
        ),
    ]
