# Generated by Django 5.2.6 on 2025-11-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecg_app', '0009_ecgimage_patient_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='echoimage',
            name='patient_country_code',
            field=models.CharField(default='+1', help_text='Country calling code', max_length=5),
        ),
        migrations.AlterField(
            model_name='ecgimage',
            name='patient_phone',
            field=models.CharField(help_text="Patient's 10-digit phone number (formatted as (XXX) XXX-XXXX)", max_length=20),
        ),
        migrations.AlterField(
            model_name='echoimage',
            name='patient_gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', help_text="Patient's gender", max_length=10),
        ),
        migrations.AlterField(
            model_name='echoimage',
            name='patient_phone',
            field=models.CharField(help_text="Patient's phone number with country code", max_length=25),
        ),
    ]
