# Generated by Django 5.1.4 on 2025-11-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecg_app', '0010_echoimage_patient_country_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecgimage',
            name='patient_country_code',
            field=models.CharField(default='+91', help_text='Country calling code', max_length=5),
        ),
        migrations.AlterField(
            model_name='ecgimage',
            name='patient_phone',
            field=models.CharField(help_text="Patient's phone number with country code", max_length=25),
        ),
        migrations.AlterField(
            model_name='echoimage',
            name='patient_country_code',
            field=models.CharField(default='+91', help_text='Country calling code', max_length=5),
        ),
    ]
