# Generated by Django 5.1.4 on 2025-11-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecg_app', '0011_add_country_code_to_ecgimage_and_update_defaults'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecgimage',
            name='patient_country_code',
        ),
        migrations.RemoveField(
            model_name='echoimage',
            name='patient_country_code',
        ),
        migrations.AlterField(
            model_name='ecgimage',
            name='patient_phone',
            field=models.CharField(help_text="Patient's 10-digit phone number (formatted as (XXX) XXX-XXXX)", max_length=20),
        ),
        migrations.AlterField(
            model_name='echoimage',
            name='patient_phone',
            field=models.CharField(help_text="Patient's 10-digit phone number (formatted as (XXX) XXX-XXXX)", max_length=20),
        ),
    ]
