# Generated by Django 5.1.4 on 2025-11-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecg_app', '0012_revert_phone_changes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='echoimage',
            old_name='image_quality',
            new_name='ef_classification',
        ),
        migrations.RenameField(
            model_name='echoimage',
            old_name='overall_impression',
            new_name='error_message',
        ),
        migrations.RemoveField(
            model_name='echoimage',
            name='analyzed_at',
        ),
        migrations.RemoveField(
            model_name='echoimage',
            name='lv_function',
        ),
        migrations.RemoveField(
            model_name='echoimage',
            name='wall_motion',
        ),
        migrations.AddField(
            model_name='echoimage',
            name='analysis_quality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='echoimage',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error')], default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='echoimage',
            name='view_classification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ecgimage',
            name='patient_phone',
            field=models.CharField(help_text="Patient's 10-digit phone number (format: XXXXXXXXXX)", max_length=20),
        ),
        migrations.AlterField(
            model_name='echoimage',
            name='echo_file',
            field=models.FileField(help_text='Upload echo video file (MP4, AVI, DICOM)', upload_to='echo_uploads/'),
        ),
        migrations.AlterField(
            model_name='echoimage',
            name='patient_phone',
            field=models.CharField(help_text="Patient's 10-digit phone number (format: XXXXXXXXXX)", max_length=20),
        ),
    ]
