# Generated by Django 5.1.4 on 2025-11-20 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecg_app', '0013_rename_image_quality_echoimage_ef_classification_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EchoImage',
        ),
    ]
