# Generated by Django 5.2.6 on 2025-11-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecg_app', '0014_delete_echoimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='EchoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(help_text="Patient's full name", max_length=255)),
                ('patient_age', models.PositiveIntegerField(help_text="Patient's age in years")),
                ('patient_dob', models.DateField(help_text="Patient's date of birth", null=True)),
                ('patient_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', help_text="Patient's gender", max_length=10)),
                ('patient_phone', models.CharField(help_text="Patient's 10-digit phone number (format: XXXXXXXXXX)", max_length=20)),
                ('echo_file', models.FileField(help_text='Upload echo video file (MP4, AVI, DICOM)', upload_to='echo_uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_results', models.JSONField(blank=True, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('view_classification', models.CharField(blank=True, max_length=100, null=True)),
                ('ejection_fraction', models.FloatField(blank=True, null=True)),
                ('ef_classification', models.CharField(blank=True, max_length=50, null=True)),
                ('analysis_quality', models.CharField(blank=True, max_length=50, null=True)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error')], default='pending', max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
